apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  mysql-root-password: {{ .Values.mysql.rootPassword | b64enc | quote }}
  mysql-user: {{ .Values.mysql.user | b64enc | quote }}
  mysql-password: {{ .Values.mysql.password | b64enc | quote }}
